version: '2.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - './pgdata/:/var/lib/postgresql/data/pgdata'
    cpu_count: 1
    cpu_percent: 50
    shm_size: 256M
  bot:
    build: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - db
    cpu_count: 1
    cpu_percent: 50
